# Generated by Django 5.2.1 on 2025-06-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vietclub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='admission',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
