# Generated by Django 5.2.1 on 2025-06-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vietclub', '0002_alter_event_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_current',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
