# Generated by Django 5.2.1 on 2025-06-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vietclub', '0003_alter_event_is_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_current',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
