# Generated by Django 5.2.1 on 2025-06-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vietclub', '0004_alter_event_attendees_alter_event_is_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(related_name='events', to='vietclub.sponsor'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(help_text='general name ex:  Movie Night', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_sub_name',
            field=models.CharField(help_text='more details about the event: Mai Movie', max_length=100),
        ),
    ]
