# Generated by Django 5.2.1 on 2025-06-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vietclub', '0005_event_sponsors_alter_event_event_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', to='vietclub.sponsor'),
        ),
    ]
