# Generated by Django 5.2.1 on 2025-06-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vietclub', '0006_alter_event_sponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='sponsor_link',
            field=models.URLField(default='https://yt3.googleusercontent.com/eXmxqdHDeAjv3Ji5_04qvu87i2Cz2TlwfadI5StpxCDj-EBqG_TkrFzu0KyKMiOvjGzRPL1pkx4=s900-c-k-c0x00ffffff-no-rj'),
            preserve_default=False,
        ),
    ]
